config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#main'
  get 'music' => 'pages#music'
  get 'about' => 'pages#about'
  get 'contacts' => 'pages#contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end

  def music
  end

  def about
  end

  def contacts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_bgimage.html.erb
<!-- Background image
<div class="bg-image"
     style="background-image: url('https://images.unsplash.com/photo-1601148071764-8c3f50e9ab20?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80');
            height: 100vh">
</div>
<!-- Background image -->

<%= image_tag('vynil.jpg') %>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4">
  <div class="col-md-4 d-flex align-items-center">
    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
      <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
    </a>
    <span class="text-dark">&copy;the MAEN 2022-<%= Time.now.year %></span>
  </div>

  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
    <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
    <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
    <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
  </ul>
</footer>

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
  <%= link_to 'the MAEN', root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'MAIN', root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'MUSIC', music_path, class:'nav-link' %>
      </li>
      <li>
        <%= link_to 'ABOUT', about_path, class:'nav-link' %>
      </li>
      <li>
        <%= link_to 'CONTACTS', contacts_path, class:'nav-link' %>
      </li>

    </ul>

    <ul>
      <li>
        <%= link_to ' SPOTIFY ', 'https://spotify.com', class:'btn btn-secondary btn-sm opacity-75'%>
          <%= link_to 'TELEGRAM', 'https://t.me/stopmenowband', class:'btn btn-secondary btn-sm opacity-75' %>
        </li>
      </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div style="background-image; height: 50px">
    <%= render 'layouts/bgimage' %>
    </div>
    <nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-transparent">
<%= render 'layouts/navbar' %>
</nav>
    <div class="container">
    <%= yield %>
    </div>

    <div class="fixed-bottom bg-transparent">
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div label="textual_info_about" class="h6 text-white opacity-75 mt-5">
  <center>
    <p>
      the MAEN is a music project created for huge fun. It allows us making whatever we would not be able to do in our "real" bands for multiple reasons.
      </p>
      <p>
        Music is vital. It is probably one of not so many things keeping us where we reside. On the other hand Music makes us feel better all the time.
        You probably already heard some of our music. But if you did not, there's a link above called "music", be sure to check it out.
        <p>
    </center>
  </div>

app/views/pages/contacts.html.erb
<div label="content" class="h6 mt-5 text-white opacity-75"><center>
  <p>Thank you for your interest. Please feel free to send email to Maen:</p>
  </center>
  </div>

<div label="contact_information" class="text-main mx-auto opacity-100"><h3>
  <center>
  <p>themaen.com[at]gmail.com</p>
  </center>
</h3>
  </div>

<div label="social_media" class="h6 text-white opacity-75 mt-5">
  <p><center>Social Media links:</center>
    </p>
  </div>

app/views/pages/music.html.erb
<div label="music" class="m-5">

<div label="song_title" class="text-warning h3 m-3 opacity-75">
  NOTHING LEFT
  </div>
  <p>
  <div label="audio_player">
    <audio src="audios/Nothing Left.mp3" controls class="w-100 opacity-75"></audio>
    </div>